options = optimoptions('fmincon', ...
            'Algorithm', ...
            'interior-point', ...
            'Display', ...
            'final');    
fun = @objectiveFunction
constraints = @nlconst
[xfinal,fval,exitflag,output2] = fmincon(...
        fun, ...
        [-1;2],...
        [],[],[],[],[],[],...
        constraints, ...
        options ...
    )