function f = objectiveFunction(x)
    f =  log(...
            1.0 ...
            +   3.0 * ( ...
                    x(2)  - (x(1) ^ 3 - x(1)) ...
                )^2 ...
            + (x(1) - 4/3)^2 ...
          ) 